name: Deploy Tolemi Website
on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  NEXT_PUBLIC_TINA_BRANCH: main
  AWS_ROLE: "arn:aws:iam::993874376304:role/github_oidc_role"
  AWS_REGION: "us-east-1"

permissions:
  id-token: write

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.12.0"

      - name: Install dependencies
        run: npm install

      - name: Build the website
        env:
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE }}

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://tolemi-website --delete
